spring.application.name=digital-signature-impression

# JWT Configuration
jwt.secret=digital-jay-2010
jwt.expiration=86400000

# Spring Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/digital_signature_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8084

springdoc.swagger-ui.path=/docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
